image: dewert/gibanica:base
stages:
  - build

after_script:
  - rm -rf build

compile:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../MudServer
    - make
  artifacts:
    paths:
    - bu
cleanup-build-folder:
  stage: cleanup
  script:
    - rm -rf build

