image: ubuntu:latest
stages:
  - build

before_script:
  - apt-get update -qq
  - apt-get install -y -qq build-essential cmake libboost-all-dev

after_script:
  - rm -rf build

compile:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../MudServer
    - make
    - cd ..
