image: alpine:latest
stages:
  - build

before_script:
  - apk update
  - apk upgrade
  - apk add build-base cmake boost-dev ncurses ncurses-dev

after_script:
  - rm -rf build

compile:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../MudServer
    - make
    - cd ..
