image: dewert/gibanica:base
stages:
  - build
  - test
  - cleanup

compile:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../MudServer
    - make
  artifacts:
    paths:
    - build

cleanup-build-folder:
  stage: cleanup
  script:
    - rm -rf build

