image: dewert/gibanica:base
stages:
  - build
  - test
  - cleanup

compile:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../MudServer
    - make
<<<<<<< HEAD

=======
>>>>>>> daadc40f63c104d98d68f948b73681792c9742b3
  artifacts:
    paths:
    - build

connection-manager-unit-test:
  stage: test
  script:
    - cd build/bin
    - ./connectionmantest | grep "PASSED"

cleanup-build-folder:
  stage: cleanup
  script:
    - rm -rf build

<<<<<<< HEAD

=======
>>>>>>> daadc40f63c104d98d68f948b73681792c9742b3
