image: dewert/gibanica:base
stages:
  - build

after_script:
  - rm -rf build

compile:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../MudServer
    - make
    - cd ..

test:
  stage: test
  script:
    - cd build/bin
    - ./runAllTests | grep "PASSED"

    
