image: dewert/gibanica:base
stages:
  - build
  - test
  - cleanup

after_script:
  - rm -rf build

compile:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../MudServer
    - make
  artifacts:
    paths:
    - build

