image: dewert/gibanica:base
stages:
  - build

after_script:

  
stages:
  - build
  - test
  - deploy
  - cleanup

compile:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../MudServer
    - make

connection-manager-unit-test:
  stage: test
  script:
    - cd build/bin
    - ./runAllTests | grep "PASSED"


remove build:
  stage: cleanup
  script:
      - rm -rf build
