image: dewert/gibanica:base
stages:
  - build


compile:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ../MudServer
    - make
<<<<<<< HEAD
  artifacts:
    paths:
    - build

connection-manager-unit-test:
  stage: test
  script:
    - cd build/bin
    - ./connectionmantest | grep "PASSED"

cleanup-build-folder:
  stage: cleanup
  script:
    - rm -rf build
=======
    - cd ..
>>>>>>> 08f722681e512ea88be65fe73327b1950903a92a
