image: dewert/gibanica:base

stages:
  - build
  - test
  - cleanup

before_script:
  - apk update
  - apk add yaml-cpp-dev
  - apk add bash
  
clang-format-check:
  stage: build
  script:
    - ./format-checker.sh

compile:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
    - build

mudserver-unit-test:
  stage: test
  script:
    - cd build
    - bin/mudtest

cleanup-build-folder:
  stage: cleanup
  script:
    - rm -rf build
