SERVER:
  port: 4000
  areas:
  - MudGameEngine/lib/dataFiles/detailed_smurf.yml
  - MudGameEngine/lib/dataFiles/detailed_midgaard.yml
  - MudGameEngine/lib/dataFiles/detailed_mgoose.yml
  spells:
  - MudGameEngine/lib/dataFiles/spells.yml
  config_dir: config
  url: localhost
CLIENT:
  port: 4000
  url: localhost

