SERVER:
  port: 4000
  yml_file: /home/jla497/CLionProjects/adventure2018/build/MudGameEngine/lib/dataFiles/detailed_midgaard.yml
  url: localhost
CLIENT:
  port: 4000
  yml_file: /home/jla497/CLionProjects/adventure2018/build/MudGameEngine/lib/dataFiles/detailed_midgaard.yml
  url: localhost